name: Defect Report
description: Report a defect/bug encountered while operating the library
labels: kind/defect
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        What you encountered
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What was supposed to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction scenario?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Any additional information

  - type: textarea
    id: version
    attributes:
      label: Library version
      value: |
       v0.0.1
    validations:
      required: true


  - type: textarea
    id: osVersion
    attributes:
      label: OS version
      value: |
        <details>

        ```console
        # On Linux:
        $ cat /etc/os-release
        # paste output here
        $ uname -a
        # paste output here

        # On Windows:
        C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
        # paste output here
        ```

        </details>
